import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";

// #121 — Groth16 trusted-setup CEREMONY MARKER.
//
// The five *CircuitGroth16Verifier.sol under contracts/contracts/verifiers are
// generated by hardhat-zkit. Today they come from a DEV trusted setup
// (hardhat.config.ts → setupSettings.contributionSettings.contributions: 0),
// which is fine for Fuji but MUST NOT back a mainnet deployment. This module is
// the single, committed source of truth that distinguishes a real multi-operator
// ceremony build from the dev build, so deploy:mainnet can refuse the dev one.
//
// The marker (marker.json, committed) records, per circuit, the sha256 of the
// verifier .sol that a given trusted setup produced, plus the ceremony metadata
// (contributions count + public random beacon). `scripts/ceremony/run-ceremony.ts`
// rewrites the marker to `build: "ceremony"` after a real phase-2 ceremony;
// until then it stays `build: "dev"` and deploy:mainnet aborts.

export const CEREMONY_CIRCUITS = [
	"registration",
	"transfer",
	"mint",
	"withdraw",
	"burn",
] as const;

export type CeremonyCircuit = (typeof CEREMONY_CIRCUITS)[number];

// Committed verifier .sol filename per circuit (under contracts/contracts/verifiers).
export const VERIFIER_SOL_BY_CIRCUIT: Record<CeremonyCircuit, string> = {
	registration: "RegistrationCircuitGroth16Verifier.sol",
	transfer: "TransferCircuitGroth16Verifier.sol",
	mint: "MintCircuitGroth16Verifier.sol",
	withdraw: "WithdrawCircuitGroth16Verifier.sol",
	burn: "BurnCircuitGroth16Verifier.sol",
};

const CONTRACTS_ROOT = path.join(__dirname, "..", "..");
export const VERIFIERS_DIR = path.join(CONTRACTS_ROOT, "contracts", "verifiers");
// Named ceremony-marker.json (not marker.json) so the "./marker" module import
// never resolves to the JSON instead of marker.ts.
export const CEREMONY_MARKER_PATH = path.join(
	__dirname,
	"ceremony-marker.json",
);

// "dev" = contributions:0 development setup (Fuji only). "ceremony" = a real
// phase-2 ceremony with >=1 independent contribution and a public beacon.
export type CeremonyBuild = "dev" | "ceremony";

export type CeremonyVerifierRecord = {
	// Repo-relative path, for humans reading the marker.
	source: string;
	// sha256 of the verifier .sol at the time the marker was written.
	sha256: string;
};

export type CeremonyMarker = {
	build: CeremonyBuild;
	provingSystem: "groth16";
	// Number of independent phase-2 contributions (0 = dev setup).
	contributions: number;
	// Public random beacon applied after the contributions (hex string), or null
	// for the dev setup. A real ceremony MUST have one.
	beacon: string | null;
	// Powers-of-Tau source used, for the transcript (null in the dev setup).
	ptau: string | null;
	// Where the published ceremony transcript/attestations live (null until run).
	transcriptUrl: string | null;
	note: string;
	verifiers: Record<CeremonyCircuit, CeremonyVerifierRecord>;
};

export type CeremonyValidation = { ok: true } | { ok: false; reason: string };

export function sha256File(filePath: string): string {
	return createHash("sha256").update(readFileSync(filePath)).digest("hex");
}

// sha256 of every committed verifier .sol on disk right now.
export function computeVerifierFingerprint(
	verifiersDir: string = VERIFIERS_DIR,
): Record<CeremonyCircuit, string> {
	return Object.fromEntries(
		CEREMONY_CIRCUITS.map((circuit) => [
			circuit,
			sha256File(path.join(verifiersDir, VERIFIER_SOL_BY_CIRCUIT[circuit])),
		]),
	) as Record<CeremonyCircuit, string>;
}

export function readCeremonyMarker(
	markerPath: string = CEREMONY_MARKER_PATH,
): CeremonyMarker {
	const parsed = JSON.parse(readFileSync(markerPath, "utf8")) as CeremonyMarker;
	if (parsed.build !== "dev" && parsed.build !== "ceremony") {
		throw new Error(
			`ceremony marker ${markerPath} has an invalid build "${String(parsed.build)}"`,
		);
	}
	if (parsed.provingSystem !== "groth16") {
		throw new Error(
			`ceremony marker ${markerPath} must be groth16; got "${String(parsed.provingSystem)}"`,
		);
	}
	return parsed;
}

// The gate deploy:mainnet enforces (#120 guardrail #4). Returns ok only when the
// marker attests a real ceremony AND the on-disk verifiers still match that
// ceremony's recorded hashes (so a dev verifier can't be swapped back in after
// the marker is flipped).
export function validateCeremonyMarker(
	marker: CeremonyMarker,
	actualHashes: Record<CeremonyCircuit, string>,
): CeremonyValidation {
	if (marker.build !== "ceremony") {
		return {
			ok: false,
			reason:
				`ceremony marker build is "${marker.build}" — the verifiers are a DEV trusted setup ` +
				"(contributions:0). Run scripts/ceremony/run-ceremony.ts and commit the regenerated " +
				"verifiers + marker before a mainnet deploy.",
		};
	}
	if (!Number.isInteger(marker.contributions) || marker.contributions < 1) {
		return {
			ok: false,
			reason: `ceremony marker has ${marker.contributions} contributions; a mainnet ceremony needs >= 1`,
		};
	}
	// A real public random beacon, not a placeholder — require >=32 bytes of hex.
	if (typeof marker.beacon !== "string" || !/^0x[0-9a-fA-F]{64,}$/.test(marker.beacon)) {
		return {
			ok: false,
			reason:
				"ceremony marker beacon must be a >=32-byte hex public random beacon (a placeholder is not accepted)",
		};
	}
	// The published transcript/attestations must be pointed to, so the ceremony is
	// auditable — a build:"ceremony" marker with no transcript is not trusted.
	if (typeof marker.transcriptUrl !== "string" || !/^https:\/\/\S+$/.test(marker.transcriptUrl)) {
		return {
			ok: false,
			reason:
				"ceremony marker must point to a published transcript (an https transcriptUrl)",
		};
	}
	for (const circuit of CEREMONY_CIRCUITS) {
		const recorded = marker.verifiers[circuit]?.sha256;
		const actual = actualHashes[circuit];
		if (recorded !== actual) {
			return {
				ok: false,
				reason:
					`${circuit} verifier sha256 ${actual} does not match the ceremony marker ` +
					`(${recorded ?? "missing"}) — the verifier changed after the ceremony`,
			};
		}
	}
	return { ok: true };
}

// Convenience for the deploy path: read the committed marker, hash the on-disk
// verifiers, and throw if this is not a real ceremony build.
export function assertCeremonyBuild(
	markerPath: string = CEREMONY_MARKER_PATH,
	verifiersDir: string = VERIFIERS_DIR,
): void {
	const marker = readCeremonyMarker(markerPath);
	const result = validateCeremonyMarker(
		marker,
		computeVerifierFingerprint(verifiersDir),
	);
	if (!result.ok) {
		throw new Error(`mainnet_ceremony_required: ${result.reason}`);
	}
}
